### ISSUE TITLE
500 internal error

### ISSUE THREAD

**Issue by dklisiaris** [dklisiaris/bookshark-http-api#3]
When no developer key has been provided, an internal server error occurs.

**Comment by dklisiaris** [comment]
From log:

```
I, [2015-04-19T19:44:53.204714 #19739]  INFO -- : Started GET "/" for 77.49.173.127 at 2015-04-19 19:44:53 +0300
I, [2015-04-19T19:44:53.210382 #19739]  INFO -- : Processing by HomeController#index as HTML
I, [2015-04-19T19:44:53.215180 #19739]  INFO -- :   Rendered home/index.html.erb within layouts/application (1.1ms)
D, [2015-04-19T19:44:53.225021 #19739] DEBUG -- :   User Load (2.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
I, [2015-04-19T19:44:53.228503 #19739]  INFO -- :   Rendered layouts/_menu.html.erb (10.5ms)
I, [2015-04-19T19:44:53.229978 #19739]  INFO -- : Completed 200 OK in 19ms (Views: 14.5ms | ActiveRecord: 2.4ms)
I, [2015-04-19T19:47:11.551028 #19736]  INFO -- : Started GET "/api/v1/book?id=104970" for 77.49.173.127 at 2015-04-19 19:47:11 +0300
I, [2015-04-19T19:47:11.556825 #19736]  INFO -- : Processing by API::V1::BookController#index as HTML
I, [2015-04-19T19:47:11.557065 #19736]  INFO -- :   Parameters: {"id"=>"104970"}
D, [2015-04-19T19:47:11.564876 #19736] DEBUG -- :   APIKey Load (2.3ms)  SELECT  "api_keys".* FROM "api_keys" WHERE "api_keys"."last_request_ip" = $1 AND "api_keys"."user_id" IS NULL LIMIT 1  [["last_request_ip", "77.49.173.127"]]
I, [2015-04-19T19:47:11.567941 #19736]  INFO -- : Completed 500 Internal Server Error in 10ms (ActiveRecord: 2.3ms)
F, [2015-04-19T19:47:11.571950 #19736] FATAL -- : 
NoMethodError (undefined method `total_requests' for nil:NilClass):
  app/models/api_key.rb:19:in `reset_requests!'
  app/models/api_key.rb:11:in `reset_if_needed!'
  app/models/api_key.rb:25:in `below_usage_limits?'
  app/controllers/api/v1/base_controller.rb:27:in `grant_access!'
```

**Comment by dklisiaris** [comment]
Fixed. It was trying to add to total requests when there was no user.
